security:
    encoders:
        UserBundle\Entity\User:      sha512

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER, ROLE_AUTHOR, ROLE_MODERATOR, ROLE_AGENT, ROLE_MANUFACTURER, ROLE_BUYER, ROLE_SELLER]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN,ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
            id:            fos_user.user_provider.username_email


    firewalls:
        dev:
            pattern:        ^/(_(profiler|wdt|error)|css|images|js)/
            security:       false

        main_login:
            pattern:        ^/login$
            anonymous:      true

        main_login:
            pattern:        ^/admin
            anonymous:      false

        main:
            pattern:        ^/
            anonymous:      true
            provider:       main
            form_login:
                provider: main
                csrf_provider: form.csrf_provider
                login_path: fos_user_security_login
                default_target_path: lld_admin
                check_path: fos_user_security_check
            logout:
                path:       fos_user_security_logout
                target:     /
            remember_me:
                key:        %secret%


    access_control:
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }


